### PR TITLE
Remove floating time window

### PR DESCRIPTION
**Pull request by thomaspeitz**

### CODE REVIEW

**Comment by thomaspeitz** [comment]
@vishalraina - Hey any opinion regarding this? - I would like to add to this PR some hints that it makes more sense to set a length of 300s but only on boot and let users define the windows.

This would simplify the code and from my opinion it is better as the current approach.

Would be a fix for #455 

As you added a lot of time logic I would be interersted in your opinion.

Greetings, Thomas

**Comment by vishalraina** [comment]
Hello, @thomaspeitz thank you for let me know.
We should put in additional changes to this PR to fix regression.
[Here are code](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/d7e93f341c8f067330b4486a43756f8edc3f14c6/main.go#L137,L174) changes we should add back.

CC @singhjagmohan1000 @ssurana

**Comment by thomaspeitz** [comment]
Hey @singhjagmohan1000,

thanks for your informations. That helped a lot.

I think we should do the following:
- We should track the time of scraping and expose it as new metric for transparency (maybe even job level based)
- Warn users in case that this issue could happen.

Currently magic happens for the user which is hard to understand.

UX was always one of the core principles while writing this.
We need to find a better way to cope with this.

Do you by any chance have a configuration example where I can see this happening? - This would allow me to live code and debug this issue and verify if there is no other solution for this problem.

**Comment by singhjagmohan1000** [comment]
@thomaspeitz 
This was one of the config that we tried.
```
discovery:
  jobs:
    - type: ec
      regions:
        - us-west-2
      period: 300
      length: 600
      delay: 600
      addCloudwatchTimestamp: true
      metrics:
        - name: BytesUsedForCache
          statistics: ['Average','Minimum','Maximum']
        - name: EngineCPUUtilization
          statistics: ['Average','Minimum','Maximum']
        - name: CacheHitRate
          statistics: ['Average','Sum','Minimum','Maximum']
        - name: CacheHits
          statistics: ['Average','Sum']
        - name: CacheMisses
          statistics: ['Average','Sum','Minimum','Maximum']
        - name: CurrConnections
          statistics: ['Average','Minimum','Maximum']
        - name: Evictions
          statistics: ['Average','Minimum','Maximum','Sum']
```
image2020-10-19_18-11-1
Screenshot of gap that was seen in between datapoints

More debug data from debugging we did on our side
```
Note: Time printed with Timestamps label are in UTC and time printed above are PDT. We can get the same time by subtracting 7H from UTC.

Reference, How we are getting values for StartTime and EndTime:

endTime := time.Now().Add(-time.Duration(delay) * time.Second)
startTime := time.Now().Add(-(time.Duration(length) + time.Duration(delay)) * time.Second)
Scrape 1:

{"level":"info","msg":"**************CurrentTime: %s 2020-10-19 17:47:46.680655 -0700 PDT m=+2.175628242","time":"2020-10-19T17:47:46-07:00"}
{"level":"info","msg":"**************StartTime: %s 2020-10-19 17:27:46.680806 -0700 PDT m=-1197.824221107","time":"2020-10-19T17:47:46-07:00"}
{"level":"info","msg":"**************EndTime: %s 2020-10-19 17:37:46.680805 -0700 PDT m=-597.824221681","time":"2020-10-19T17:47:46-07:00"}

Timestamps: [2020-10-20 00:32:00 +0000 UTC,2020-10-20 00:27:00 +0000 UTC]

Scrape 2:

{"level":"info","msg":"**************CurrentTime: %s 2020-10-19 17:52:50.652843 -0700 PDT m=+306.139219919","time":"2020-10-19T17:52:50-07:00"}
{"level":"info","msg":"**************StartTime: %s 2020-10-19 17:32:50.65295 -0700 PDT m=-893.860672858","time":"2020-10-19T17:52:50-07:00"}
{"level":"info","msg":"**************EndTime: %s 2020-10-19 17:42:50.652949 -0700 PDT m=-293.860673389","time":"2020-10-19T17:52:50-07:00"}

Timestamps: [2020-10-20 00:37:00 +0000 UTC,2020-10-20 00:32:00 +0000 UTC]

Scrape 3:

{"level":"info","msg":"**************CurrentTime: %s 2020-10-19 17:57:54.826038 -0700 PDT m=+610.303290270","time":"2020-10-19T17:57:54-07:00"}
{"level":"info","msg":"**************StartTime: %s 2020-10-19 17:37:54.826137 -0700 PDT m=-589.696610372","time":"2020-10-19T17:57:54-07:00"}
{"level":"info","msg":"**************EndTime: %s 2020-10-19 17:47:54.826137 -0700 PDT m=+10.303389115","time":"2020-10-19T17:57:54-07:00"}

Timestamps: [2020-10-20 00:42:00 +0000 UTC,2020-10-20 00:37:00 +0000 UTC]

Scrape 4: 

{"level":"info","msg":"**************CurrentTime: %s 2020-10-19 18:02:58.973908 -0700 PDT m=+914.442036591","time":"2020-10-19T18:02:58-07:00"}
{"level":"info","msg":"**************StartTime: %s 2020-10-19 17:42:58.974011 -0700 PDT m=-285.557860801","time":"2020-10-19T18:02:58-07:00"}
{"level":"info","msg":"**************EndTime: %s 2020-10-19 17:52:58.97401 -0700 PDT m=+314.442138665","time":"2020-10-19T18:02:58-07:00"}

Timestamps: [2020-10-20 00:47:00 +0000 UTC,2020-10-20 00:42:00 +0000 UTC]

Scrape 5:

{"level":"info","msg":"**************CurrentTime: %s 2020-10-19 18:08:03.415362 -0700 PDT m=+1218.888431465","time":"2020-10-19T18:08:03-07:00"}
{"level":"info","msg":"**************StartTime: %s 2020-10-19 17:48:03.415461 -0700 PDT m=+18.888530453","time":"2020-10-19T18:08:03-07:00"}
{"level":"info","msg":"**************EndTime: %s 2020-10-19 17:58:03.41546 -0700 PDT m=+618.888529867","time":"2020-10-19T18:08:03-07:00"}

Timestamps: [2020-10-20 00:53:00 +0000 UTC,2020-10-20 00:48:00 +0000 UTC]

We can see the gap on Grafana Screen shot below, occurred at this point.

What happened, We can see Values of StartTime in different scrapes:

Scrape 1: 17:27:46
Scrape 2: 17:32:50
Scrape 3: 17:37:54
Scrape 4: 17:42:58
Scrape 5: 17:48:03
We can see that at each scrape StartTime is increased with 5m that we can relate to sleeping time.

But also there is an extra 4s added each time, and then when these 4s add up to next minute we are missing the datapoint by 1m timestamp.

**Comment by vishalraina** [comment]
Thank you @singhjagmohan1000 for sharing detailed information on what caused issues.
@thomaspeitz sorry for the late response I had too many things going on for the last 2 months.
Here is a more detailed explanation for new code changes:
In order to remember the last script log what changed from calculation time interval now - 5min(scrape interval) to last scrape time + length in the namespace. 
Now that we had time to the last scrape it brings further timestamp issues.

Let us consider the following use case:
  YACE scrape interval: 5m(time to sleep between scrapes)
     type:ec
     Length(in for type ec): 600(10m)
     Delay(in for type ec): 600(10m)
    Scrape start time: 1500 hrs
YACE start time 1500hrs
As per this configuration 
starttime: 1440 hrs
endtime:1450 hrs

YACE second scrape time 1505hrs(after 5 in sleep)
endtime=starttime=1450hrs
newendtime=starttime+length=1505hrs

YACE thrid scrape time 1510hrs(after 5 in sleep)
endtime=starttime=1505hrs
newendtime=starttime+length=1515hrs which is in future.
Due to this both delay and future timestamps become issues. Part of the reason why this bug occurred.

To avoid I did 2 things one make sure sleep is not less than the length of the config file with [this code change](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/d7e93f341c8f067330b4486a43756f8edc3f14c6/main.go#L131,L132).

2nd make sure to adjust sleep time so that we do not fall back [this code](https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/d7e93f341c8f067330b4486a43756f8edc3f14c6/main.go#L137,L174) lines were introduced.

Here is my attempt to explain what issue we faced:


yace_timestamp_issue
In case I still have your attending debugging yace is extremely hard we just expose standard go metrics that all go exporters expose part of yace /metrics URLs these come extremely handy during debugging process.


Happy to get on a call to talk more about this, evening PST hours work best for me on weekdays.

**Comment by thomaspeitz** [comment]
Would be interested in more contributors opinion on changing the whole scraping logic / removing cache (see my last comment)
cc: @jylitalo / @cristiangreco / @rabunkosar-dd / @andyzasl / @arvidsnet / @AndrewChubatiuk 

Thanks for your inputs <3

**Comment by andyzasl** [comment]
Hi!
From my perspective, Prometheus should do scraping work, while yace - gathering data work. 
Moreover, in any kind of a few scrapers design, we'll have to configure each scraper. 

So, my opinion is - to let the yace do his work in the most efficient style while keeping in mind, that we might want to scrape it a lot often than the specified time. 

Caching is also the major part - cause we have a API calls limit :)


Btw, in https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/456#issuecomment-945236692
I see something strange, we want to ask for data for 10 min, every 5 min. 
It's not clear for me - why?

**Comment by thomaspeitz** [comment]
Closing in favour of https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/480

**Pull request closed without merging**
