### PR TITLE
buildx command releasing multi arch Docker images

### PR DESCRIPTION
**Pull request by jlamande**
Using docker buildx command to build and release Docker images with multiple architectures support.

Fixes https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/484

Replaces https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/487

Goal: obtain the image with the same name and the same tag but with different architectures. 

Using different architectures provides to the docker/containerd/... daemons the ability to take automatically the best image for their current running architecture transparently for the end-users.

### CODE REVIEW

**Comment by jlamande** [comment]
looking forward to the next release 🤞🏻

**Comment by thomaspeitz** [comment]
Verifying if I get feedback of https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/490 - Then I can put it into one release.

Will release tomorrow morning hopefully with the other PR as well <3

Else I add some more debugging logging.

**Comment by thomaspeitz** [comment]
@jlamande - Reverting your change. Did not work sadly and I currently have no time to debug the buildx things.

**Comment by jlamande** [comment]
No pb @thomaspeitz. I understand.

Sorry not being able to easily reproduce the thing. I will check it : https://github.com/nerdswords/yet-another-cloudwatch-exporter/runs/4484552861?check_suite_focus=true

**Comment by jlamande** [comment]
the step that failed is "Is Release published ?"

```
    - name: Is release published?
      if: github.event.action != 'published'
      run: exit 78
```

I don't get the point.

**Pull request merged**
