### PR TITLE
Fix DX metrics DimensionRegexps

### PR DESCRIPTION
**Pull request by paulojmdias**
This PR fixes https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/176

### CODE REVIEW

**Comment by paulojmdias** [comment]
@thomaspeitz can you please review it? Without this fix, the metrics for `AWS/DX` will not work in `discovery` mode.

**Comment by paulojmdias** [comment]
@cristiangreco @thomaspeitz can you help me with this merge and release?

**Review by cristiangreco — APPROVED** [review]
Thanks!

**Comment by sambenj** [comment]
Hi @paulojmdias - can you share some example cfg for this? I've defined the following but receive no metrics:

`
discovery:
  jobs:
  - type: dx
    regions:
      - eu-west-2
    searchTags:
      - key: MYKEY
        value: MYVALUE
    roles:
      - roleArn: "MYROLE"
    metrics:
    - name: ConnectionState
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: ConnectionBpsEgress
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: ConnectionBpsIngress
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: ConnectionPpsEgress
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: ConnectionPpsIngress
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: ConnectionErrorCount
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: ConnectionLightLevelTx
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: ConnectionLightLevelRx
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: VirtualInterfaceBpsEgress
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: VirtualInterfaceBpsIngress
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: VirtualInterfacePpsEgress
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600
    - name: VirtualInterfacePpsIngress
      statistics: [ Sum, Maximum, Minimum, Average ]
      period: 300
      length: 3600`

is `dimensions` with `ConnectionId` needed for this, or can it pick up all connections?

Thanks!

**Pull request merged**
