### PR TITLE
Add helm chart

### PR DESCRIPTION
**Pull request by vkobets**
This PR closes https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/491 https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/5.
This change adds a helm chart.
Code is prepared to use github.io as a helm registry, https://github.com/helm/chart-releaser-action

It is not tested yet.

I would be happy if someone would test it.

https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/605

https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/605#issuecomment-1169554064
>Awesome - Thats nice to see!
>
>Could you please test it yourself first and if you are sure it works, tag me and then I would like to review <3
>
>As I am a private person maintaining this I really depend that I have contributions which take as less private time away from >me as possible.
>
>Is the helm chart based on: https://artifacthub.io/packages/helm/mogaal/prometheus-yace-exporter - If not what are >differences? :) - Thanks!

the message gave me an idea to merge this repo and then update that code.
So now differences are
- renamed chart
- updated README.md
- updated templates according to common helm chart template(helm create)
- fixed notes
- fixed healthcheck
- added imagePullSecrets
- added PrometheusRule
- added pipelines for helm, it cant be tested before the merge.

### CODE REVIEW

**Comment by thomaspeitz** [comment]
Please add chart and docs to a deploy directory and link the deploy/helm.md and the deploy/helm/.... (chart)
from the big README.md e.g.

# Install
*Install via HELM [link to deploy/helm.md]

This way we can support multiple installations / deployment methods.

Thank you <3

**Comment by vkobets** [comment]
Pipeline is tested

Please create an empty branch for helm repo with name `gh-pages`
```bash
$ git checkout --orphan gh-pages
# preview files to be deleted
$ git rm -rf --dry-run .
# actually delete the files
$ git rm -rf .
$ git commit --allow-empty -m "Initial commit on gh-pages branch"
$ git push --set-upstream origin gh-pages
```

**Comment by vkobets** [comment]
@thomaspeitz It works for me.

**Comment by vkobets** [comment]
> Please add chart and docs to a deploy directory and link the deploy/helm.md and the deploy/helm/.... (chart) from the big README.md e.g.
> 
> # Install
> *Install via HELM [link to deploy/helm.md]
> 
> This way we can support multiple installations / deployment methods.
> 
> Thank you <3

Done

**Comment by thomaspeitz** [comment]
Awesome - Thanks a lot.

I have not much time today and want to quick fire a release but your PR will be merged with next release :)

**Comment by AljoschaP** [comment]
Can confirm that it works like a charm :+1: Thank you :smiley_cat:

**Comment by ede-n** [comment]
Thanks for the work on this. 

Any ETA on the next release? @thomaspeitz

**Comment by michaelkuty** [comment]
:+1: ping response to merge this :)

**Comment by thomaspeitz** [comment]
Sorry that it took so long! <3 - Awesome feature! - Will use it myself :)

**Comment by Jeinhaus** [comment]
Is it possible, that the helm repository is not set up yet? There is no gh-pages branch where the chart repository should supposedly be.
If I follow the [tldr section](https://github.com/nerdswords/yet-another-cloudwatch-exporter/tree/master/charts/yet-another-cloudwatch-exporter#tldr) I get a 404:

```
❯ helm repo add nerdswords https://nerdswords.github.io/yet-another-cloudwatch-exporter
Error: looks like "https://nerdswords.github.io/yet-another-cloudwatch-exporter" is not a valid chart repository or cannot be reached: failed to fetch https://nerdswords.github.io/yet-another-cloudwatch-exporter/index.yaml : 404 Not Found
```
Is there something missing?

**Comment by vkobets** [comment]
> Is it possible, that the helm repository is not set up yet? There is no gh-pages branch where the chart repository should supposedly be. If I follow the [tldr section](https://github.com/nerdswords/yet-another-cloudwatch-exporter/tree/master/charts/yet-another-cloudwatch-exporter#tldr) I get a 404:
> 
> ```
> ❯ helm repo add nerdswords https://nerdswords.github.io/yet-another-cloudwatch-exporter
> Error: looks like "https://nerdswords.github.io/yet-another-cloudwatch-exporter" is not a valid chart repository or cannot be reached: failed to fetch https://nerdswords.github.io/yet-another-cloudwatch-exporter/index.yaml : 404 Not Found
> ```
> 
> Is there something missing?

@thomaspeitz https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/610#issuecomment-1173959558

**Comment by suryam27** [comment]
@Jeinhaus I'm having the same issue, any work around at the moment?

**Comment by thomaspeitz** [comment]
Hey,

sorry it is merged but not released yet - Will do so tomorrow.

Will update docs in the meantime!

Sorry folks <3

@vkobets  @Jeinhaus

**Comment by justinwyer** [comment]
Anything I can do to help get this released? In the mean time I will release this chart to our private repo and give it a go :)

**Comment by justinwyer** [comment]
@vkobets @thomaspeitz I was testing out the github actions on a fork and I was only able to get release charts running the action on the master branch if `release_helm.yml` is run on tags then it just results in:
```
Looking up latest tag...
Discovering changed charts since 'v0.40.0-helm-chart'...
Nothing to do. No chart changes detected.
```

This is due to how the action checks if it should release, comparing the commit it is being run on to diff against the last tag https://github.com/helm/chart-releaser-action/blob/main/cr.sh#L57-L82

How would you like chart releasing to work? I don't imagine the chart updating too frequently. A couple of ideas came to mind:

- `release_helm.yml` runs on `master`
- `release_helm.yml` is a manual action

Would either of these be suitable?

**Pull request merged**
