### PR TITLE
Add support for loading env

### PR DESCRIPTION
**Pull request by antoniomerlin**
This provide way to modified default value for port , debug flag, scrapping interval & metrics per query just by setting  in env or else default defined value will load.

### CODE REVIEW

**Comment by thomaspeitz** [comment]
Hey @antoniomerlin,

I like the idea but I think we should migrate to a library for cli parsing instead of writing stuff ourselves:
- https://github.com/urfave/cli/blob/master/docs/v2/manual.md#values-from-the-environment

Would you have interest to do it?

Greetings, Thomas

**Comment by thomaspeitz** [comment]
https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/435 - This would solve this issue as well.

**Comment by antoniomerlin** [comment]
yup sure i implement it but what other option currently need to provide (debug, config, scrapingInterval, metricsPerQuery)

**Comment by antoniomerlin** [comment]
And should i continue implementing in this branch

**Comment by antoniomerlin** [comment]
closing this pull request & implementing urfave/cli on origin/feature-urfave-cli-v2-impl branch

**Pull request closed without merging**
